# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import builtins
import typing

import numpy.typing
from wyvern import kernels

__all__ = [
    "interpolate_kernel",
    "interpolate_kernel_weighted",
    "interpolate_linear",
    "interpolate_linear_weighted",
]

def interpolate_kernel(
    x_in: numpy.typing.NDArray[typing.Any],
    x_out: numpy.typing.NDArray[typing.Any],
    kernel: kernels.LanczosKernel | kernels.KaiserBesselKernel | kernels.BoxcarKernel,
    y_in: numpy.typing.NDArray[typing.Any],
    *,
    scale: builtins.float = 1.0,
    y_out: numpy.typing.NDArray[typing.Any] | None = None,
) -> numpy.typing.NDArray[typing.Any]:
    r"""
    Interpolate a 2D array using a provided kernel.

    Parameters
    ----------
    x_in
        1D float64 sorted array with input sample indices.
    x_out
        1D float64 sorted array with output sample indices. Must have uniform spacing.
    kernel
        [`AnyKernel`] instance describing the interpolation kernel.
    y_in
        2D float or complex float array to be interpolated. Must be C-contiguous.
    scale
        Optional kernel scaling factor. The inverse is multiplied with the sample spacing
        before evaluating the kernel at each input sample. Default is `1.0`.
    y_out
        Optional 2D float or complex float array to store output. Must be C-contiguous.
        If `None`, a new array is allocated. Default is None.

    Returns
    -------
    y_out
        2D float or complex float array, shape `(-1, n_out)`.

    Errors
    ------
    Raises `ValueError` when the kernel or coordinates are invalid; raises `TypeError`
    for unsupported dtypes or invalid kernel objects.
    """

def interpolate_kernel_weighted(
    x_in: numpy.typing.NDArray[typing.Any],
    x_out: numpy.typing.NDArray[typing.Any],
    kernel: kernels.LanczosKernel | kernels.KaiserBesselKernel | kernels.BoxcarKernel,
    y_in: numpy.typing.NDArray[typing.Any],
    w_in: numpy.typing.NDArray[typing.Any],
    *,
    scale: builtins.float = 1.0,
    y_out: numpy.typing.NDArray[typing.Any] | None = None,
    w_out: numpy.typing.NDArray[typing.Any] | None = None,
    propagate_mask: builtins.bool = True,
) -> tuple[numpy.typing.NDArray[typing.Any], numpy.typing.NDArray[typing.Any]]:
    r"""
    Interpolate a 2D array with corresponding weights using a kernel.

    Parameters
    ----------
    x_in
        1D float64 sorted array with input sample indices.
    x_out
        1D float64 sorted array with output sample indices. Must have uniform spacing.
    kernel
        [`AnyKernel`] instance describing the interpolation kernel.
    y_in
        2D float or complex float array to be interpolated. Must be C-contiguous.
    w_in
        2D float array of inverse-variance sample weights. Weights are propagated by
        inverting the propagated variances. Must be C-contiguous.
    scale
        Optional kernel scaling factor. The inverse of this value is multiplied with the
        sample spacing before evaluating the kernel at each input sample. Default is `1.0`.
    y_out
        Optional 2D float or complex float array to store output. Must be C-contiguous.
        If `None`, a new array is allocated. Default is None.
    w_out
        Optional 2D float array to store propagated weights. Must be C-contiguous. If
        `None`, a new array is allocated. Default is None.
    propagate_mask
        Optional flag to enable or disable input mask propagation into
        interpolated samples. Default is True.

    Returns
    -------
    y_out
        2D float or complex float array, shape `(-1, n_out)`.
    w_out
        2D float array, shape `(-1, n_out)`.

    Errors
    ------
    Raises `ValueError` when the kernel, coordinates, or weighting arrays are invalid;
    raises `TypeError` for unsupported dtypes.
    """

def interpolate_linear(
    x_in: numpy.typing.NDArray[typing.Any],
    x_out: numpy.typing.NDArray[typing.Any],
    y_in: numpy.typing.NDArray[typing.Any],
    *,
    y_out: numpy.typing.NDArray[typing.Any] | None = None,
) -> numpy.typing.NDArray[typing.Any]:
    r"""
    Linearly interpolate a 2D array.

    Parameters
    ----------
    x_in
        1D float64 sorted array with input sample indices.
    x_out
        1D float64 sorted array with output sample indices. Must have uniform spacing.
    y_in
        2D float or complex float array to be interpolated. Must be C-contiguous.
    y_out
        Optional 2D float or complex float array to store output. Must be C-contiguous.
        If `None`, a new array is allocated. Default is None.

    Returns
    -------
    y_out
        2D float or complex float array, shape `(-1, n_out)`.

    Errors
    ------
    Raises `ValueError` when the input coordinates are not sorted, repeated, or have
    incompatible dimensionality; raises `TypeError` for unsupported dtypes.
    """

def interpolate_linear_weighted(
    x_in: numpy.typing.NDArray[typing.Any],
    x_out: numpy.typing.NDArray[typing.Any],
    y_in: numpy.typing.NDArray[typing.Any],
    w_in: numpy.typing.NDArray[typing.Any],
    *,
    y_out: numpy.typing.NDArray[typing.Any] | None = None,
    w_out: numpy.typing.NDArray[typing.Any] | None = None,
    propagate_mask: builtins.bool = True,
) -> tuple[numpy.typing.NDArray[typing.Any], numpy.typing.NDArray[typing.Any]]:
    r"""
    Linearly interpolate a 2D array with corresponding weights.

    Parameters
    ----------
    x_in
        1D float64 sorted array with input sample indices.
    x_out
        1D float64 sorted array with output sample indices. Must have uniform spacing.
    y_in
        2D float or complex float array to be interpolated. Must be C-contiguous.
    w_in
        2D float array of inverse-variance sample weights. Weights are propagated by
        propagating variances and inverting the result. Must be C-contiguous.
    y_out
        Optional 2D float or complex float array to store output. Must be C-contiguous.
        If `None`, a new array is allocated. Default is None.
    w_out
        Optional 2D float array to store propagated weights. Must be C-contiguous. If
        `None`, a new array is allocated. Default is None.
    propagate_mask
        Optional flag to enable or disable input mask propagation into
        interpolated samples. Default is True.

    Returns
    -------
    y_out
        2D float or complex float array, shape `(-1, n_out)`.
    w_out
        2D float array, shape `(-1, n_out)`.

    Errors
    ------
    Raises `ValueError` for invalid dimensions, unsorted coordinates, or malformed
    weight arrays; raises `TypeError` when the dtypes are unsupported.
    """
