# Auto-generated by rylai. Do not edit manually.

import typing as t

import numpy

__all__ = [
    "interpolate_linear",
    "interpolate_linear_weighted",
]

# Module: interprs
def interpolate_linear(
    x_in: numpy.ndarray, x_out: numpy.ndarray, y_in: numpy.ndarray
) -> numpy.ndarray:
    """
    Linearly interpolate a 2D array.

    Parameters
    ----------
    ``x_in``, ``x_out`` : 1D float64 arrays (sorted; ``x_out`` should have uniform spacing)
    ``y_in``: 2D float array, shape (-1, ``n_in``)

    Returns
    -------
    ``y_out`` : 2D float array, shape (-1, ``n_out``)
    """

def interpolate_linear_weighted(
    x_in: numpy.ndarray, x_out: numpy.ndarray, y_in: numpy.ndarray, w_in: numpy.ndarray
) -> tuple[numpy.ndarray, numpy.ndarray]:
    """
    Linearly interpolate a 2D array with corresponding weights.

    Parameters
    ----------
    ``x_in``, ``x_out`` : 1D float64 arrays (sorted; ``x_out`` should have uniform spacing)
    ``y_in``: 2D float array, shape (-1, ``n_in``)
    ``w_in`` : 2D float array, same shape as ``y_in``

    Returns
    -------
    ``y_out``,``w_out`` : 2D float arrays, shape (-1, ``n_out``)
    """
