[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
profile = "release"
editable-profile = "release-with-debug-info"
features = ["mimalloc", "extension-module", "pyo3/experimental-inspect"]
manifest-path = "Cargo.toml"
frozen = false
locked = false
bindings = "pyo3"
compatibility = "pypi"
auditwheel = "repair"
strip = true
