# This file is automatically generated by pyo3_stub_gen

import builtins
import typing

__all__ = [
    "BoxcarKernel",
    "KaiserBesselKernel",
    "LanczosKernel",
]

@typing.final
class BoxcarKernel:
    r"""
    Python wrapper around a concrete Rust kernel implementation.
    """
    def __new__(cls, ntaps: builtins.int) -> BoxcarKernel:
        r"""
        Create a new kernel wrapper.

        Parameters
        ----------
        ntaps
            Number of kernel taps.
        """
    def __repr__(self) -> builtins.str: ...
    def evaluate(self, x: builtins.float) -> builtins.float: ...
    def half_width(self) -> builtins.float: ...
    def ntaps(self) -> builtins.int: ...
    def set_ntaps(self, ntaps: builtins.int) -> None: ...

@typing.final
class KaiserBesselKernel:
    r"""
    Python wrapper around a concrete Rust kernel implementation.
    """
    def __new__(cls, ntaps: builtins.int) -> KaiserBesselKernel:
        r"""
        Create a new kernel wrapper.

        Parameters
        ----------
        ntaps
            Number of kernel taps.
        """
    def __repr__(self) -> builtins.str: ...
    def evaluate(self, x: builtins.float) -> builtins.float: ...
    def half_width(self) -> builtins.float: ...
    def ntaps(self) -> builtins.int: ...
    def beta(self) -> builtins.float: ...
    def set_ntaps(self, ntaps: builtins.int) -> None: ...
    def set_beta(self, beta: builtins.float) -> None: ...
    def set_beta_default(self) -> None: ...

@typing.final
class LanczosKernel:
    r"""
    Python wrapper around a concrete Rust kernel implementation.
    """
    def __new__(cls, ntaps: builtins.int) -> LanczosKernel:
        r"""
        Create a new kernel wrapper.

        Parameters
        ----------
        ntaps
            Number of kernel taps.
        """
    def __repr__(self) -> builtins.str: ...
    def evaluate(self, x: builtins.float) -> builtins.float: ...
    def half_width(self) -> builtins.float: ...
    def ntaps(self) -> builtins.int: ...
    def set_ntaps(self, ntaps: builtins.int) -> None: ...
