# This file is automatically generated by pyo3_stub_gen

import builtins
import typing

__all__ = [
    "KaiserBesselKernel",
    "LanczosKernel",
]

@typing.final
class KaiserBesselKernel:
    def __new__(cls, ntaps: builtins.int) -> KaiserBesselKernel: ...

@typing.final
class LanczosKernel:
    def __new__(cls, ntaps: builtins.int) -> LanczosKernel: ...
