---
name: interprs-ci-tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  # CARGO_INCREMENTAL: 0

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          # share cache across jobs
          shared-key: "ci-cache"
          # prevent cross-os issues
          prefix-key: "${{ runner.os }}-rust wv"
      - run: cargo clippy -- -D warnings
      - run: cargo clippy --release -- -D warnings

  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
        with:
          # share cache across jobs
          shared-key: "ci-cache"
          # prevent cross-os issues
          prefix-key: "${{ runner.os }}-rust wv"
      - name: Run unit tests in debug
        run: cargo nextest run --profile ci --no-tests="warn"
      - name: Run unit tests in release
        run: cargo nextest run --profile ci --release --no-tests="warn"

