---
name: wyvern-ci-tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  # CARGO_INCREMENTAL: 0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      # Even with workflow-specific keys, cached builds seem to have a tendency
      # to fail on GitHub ubuntu runners (26-08-2026)
      # - uses: Swatinem/rust-cache@v2
      #   with:
      #     # share cache across jobs
      #     shared-key: "ci-cache-${{ github.workflow }}"
      #     # prevent cross-os issues
      #     prefix-key: "${{ runner.os }}-rust"
      - name: Install python 3.14
        run: uv python install 3.14
      - uses: extractions/setup-just@v4
      - run: just clippy
      - run: just check-stubs

  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@nextest
      # - uses: Swatinem/rust-cache@v2
      #   with:
      #     # share cache across jobs
      #     shared-key: "ci-cache-${{ github.workflow }}"
      #     # prevent cross-os issues
      #     prefix-key: "${{ runner.os }}-rust"
      - uses: extractions/setup-just@v4
      - name: Run unit tests
        run: just test
      - name: Run unit tests in release
        run: cargo nextest run --workspace --profile ci --release --no-tests="warn"

