---
name: interprs-deploy-docs
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          # share cache across jobs
          shared-key: "ci-cache"
          # prevent cross-os issues
          prefix-key: "${{ runner.os }}-rust wv"
      - name: Build docs
        run: cargo doc --no-deps --document-private-items
      - name: Add redirect index.html
        run: |
          echo "<meta http-equiv=\"refresh\" content=\"0; url=interprs/index.html\">" > target/doc/index.html
          touch target/doc/.nojekyll
      - name: Fix permissions
        run: chmod -c -R +rX "target/doc/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/doc

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

