"""Basic sanity checks for the top-level `wyvern` package."""

import wyvern


def test_package_exposes_version():
    # the version string is generated by maturin from Cargo.toml
    assert isinstance(wyvern.__version__, str)
    assert wyvern.__version__


def test_package_exposes_submodules():
    # `interpolate` and `kernels` should be importable as submodules
    assert hasattr(wyvern, "interpolate")
    assert hasattr(wyvern, "kernels")
